services:

  postgres:
    image: "postgres:14.2"
    restart: always
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestao_ti
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "54321:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./api
      dockerfile: backend.dockerfile
    networks:
      - backend
    ports:
      - "8080:80"
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge